<div class="card">

    <div class="card-table">

        <table class="table table-striped">
            <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Actions</th>
            </thead>
            <tbody>
            <?php foreach (\Mooshroom\Model\Worlds::getAll() as $world) {  ?>
                <tr>
                    <td><?=$host->get('id')?></td>
                    <td><?=$host->get('name')?></td>
                    <td><a href="/hosts/<?=$host->getId()?>/detail"><i class="ti-pencil"></i></a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>

    <div class="card-footer text-center">
        <a href="/worlds/create/new"><button class="btn btn-success btn-center">Create new world</button></a>
    </div>

</div>


