
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentallela Alela! | </title>

    <!-- Bootstrap -->
    <link href="/node_modules/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/node_modules/gentelella/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">


    <!-- Custom Theme Style -->
    <link href="/node_modules/gentelella/build/css/custom.min.css" rel="stylesheet">
</head>

<body class="login">
<div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
        <div class="form login_form">
            <section class="login_content">
                <form method="post" action="/">
                    <h1>Login</h1>
                    <div>
                        <input name="user" type="text" class="form-control" placeholder="Username" />
                    </div>
                    <div>
                        <input name="pass" type="password" class="form-control" placeholder="Password" />
                    </div>
                    <div>
                        <input type="submit" class="btn btn-default submit" value="Log in">
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>
</body>
</html>