<?php
    $nav = array(
        array(
            'url'    => '/server',
            'title'  => 'Minecraft Server',
            'active' => false,
            'icon'   => 'ti-server',
        ),
        array(
            'url'   => '/hosts',
            'title' => 'Hosts',
            'active' => false,
            'icon'   => 'ti-harddrives',
        ),
        array(
            'url'   => '/upload/index/binaries',
            'title' => 'Binaries',
            'active' => false,
            'icon'   => 'ti-folder',
        ),
        array(
            'url'   => '/upload/index/plugins',
            'title' => 'Plugins',
            'active' => false,
            'icon'   => 'ti-plug',
        ),
        array(
            'url'   => '/upload/index/schematics',
            'title' => 'Schematics',
            'active' => false,
            'icon'   => 'ti-gallery',
        ),
    );
?>
<ul class="nav">
    <?php foreach ($nav as $k => $v) { ?>
    <li class="">
        <a href="<?=$v['url']?>">
            <i class="<?=$v['icon']?>"></i>
            <p><?=$v['title']?></p>
        </a>
    </li>
    <?php } ?>
</ul>

