<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="card">
                    <div class="header">
                    </div>

                    <?php if (count($this->files) == 0) { ?>
                        <div class="content">
                            No files.
                        </div>
                    <?php } else { ?>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <thead>
                                    <th>File</th>
                                    <th>Action</th>
                                </thead>
                                <tbody id="filelist">
                                <?php foreach ($this->files as $file) { ?>
                                    <tr>
                                        <td><?=$file?></td>
                                        <td></td>
                                    </tr>
                                <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    <?php } ?>
                </div>

                <div class="card">
                    <div class="header">
                        Upload from Computer
                    </div>
                    <div class="content">
                        <form action="/upload/upload/<?=$this->getParam('type')?>" class="js-upload form-horizontal form-label-left" method="post">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="files[]">Upload from Computer</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div id="uploadinput">
                                        <input data-target="/ajax/upload" type="file" name="files[]" multiple>
                                    </div>
                                    <div id="progress" class="progress" style="display:none">
                                        <div class="progress-bar progress-bar-success"></div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="card">
                    <div class="header">
                        Upload from Url
                    </div>
                    <div class="content">
                        <form action="/upload/uploadurl/<?=$this->getParam('type')?>" class="js-uploadurl form-horizontal form-label-left" method="post">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="delete">Url</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="input-group">
                                        <input type="text" name="url" autocomplete="false" class="form-control">
                                        <span class="input-group-btn">
                                                <input type="submit" class="btn btn-danger" value="Upload">
                                          </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <?php if ($this->getParam('type') == 'binaries') { ?>
                <div class="card">
                    <div class="header">
                        Upload vanilla from mojang
                    </div>
                    <div class="content">
                        <form action="/upload/uploadurl/<?=$this->getParam('type')?>" class="js-uploadurl form-horizontal form-label-left" method="post">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="delete">Upload from Url</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="input-group">
                                        <select name="url" class="form-control">
                                            <?php foreach (\Mooshroom\Mojang::getDownloadUrls() as $k => $v) { ?>
                                                <option value="<?=htmlspecialchars($v)?>">minecraft_server.<?=$k?></option>
                                            <?php } ?>
                                        </select>
                                        <span class="input-group-btn">
                                            <input type="submit" class="btn btn-danger" value="Upload">
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <?php } ?>


            </div>


        </div>
    </div>
</div>




<script>
    $(function () {

        $('.js-uploadurl').submit(function(e) {
            e.preventDefault();
            $.post( $(this).attr('action'), $(this).serialize(), function(data) {
                $.each(data.result, function (index, file) {
                    $('#filelist').append( $('<tr><td>' + file + '</td><td></td></tr>') ); // text(file).appendTo('#files');
                });

            });

        });

        $('.js-upload').fileupload({

            url: $(this).data('target'),
            dataType: 'json',
            done: function (e, data) {
                $.each(data.result, function (index, file) {
                    $('#filelist').append( $('<tr><td>' + file + '</td><td></td></tr>') ); // text(file).appendTo('#files');
                });
                $('#progress').hide();
                $('#uploadinput').show();
            },
            progressall: function (e, data) {
                $('#progress').show();
                $('#uploadinput').hide();

                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('#progress .progress-bar').css(
                    'width',
                    progress + '%'
                );
            }
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
</script>