<div class="card">


    <div class="card-table">

        <table class="table table-striped">
            <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Hostname/IP</th>
            <th>Actions</th>
            </thead>
            <tbody>
            <?php foreach ($this->hosts as $host) {  ?>
                <tr>
                    <td><?=$host->get('id')?></td>
                    <td><?=$host->get('name')?></td>
                    <td><?=$host->get('hostname')?></td>
                    <td>...</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>

    <div class="card-content">
        To add a new host, log in as root to the new server and execute the installer script:
        <div style="font-family:courier,serif;color:#eee;background-color:#000;padding:5px;">
            wget -O - http://<?=$_SERVER['SERVER_NAME']?>/api/getinstaller &gt; install.php; php install.php node<br>
        </div>

    </div>

</div>


