<div class="card-content" >
<div class="nav-tabs-navigation" style="margin-bottom:10px">
    <div class="nav-tabs-wrapper">
        <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
            <li class="<?=$this->_params['action']=='general'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/general">General</a></li>
            <li class="<?=$this->_params['action']=='serverproperties'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/serverproperties">server.properties</a></li>
            <li class="<?=$this->_params['action']=='gamerules'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/gamerules">Gamerules</a></li>
            <li class="<?=$this->_params['action']=='pluginsc'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/pluginsc">Config Files</a></li>
            <li class="<?=$this->_params['action']=='plugins'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/plugins">Plugins</a></li>
            <li class="<?=$this->_params['action']=='whitelist'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/whitelist">Whitelist</a></li>
            <li class="<?=$this->_params['action']=='ops'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/ops">Ops</a></li>
            <li class="<?=$this->_params['action']=='console'?'active':''?>"><a href="/server/<?=$this->server->getId()?>/console">Console</a></li>
        </ul>
    </div>
</div>
</div>