<div class="col-md-12">

    <?php include '_control.phtml'; ?>

    <div class="card">

        <?php include '_tabs.phtml'; ?>

        <div class="card-content top-0">
            <div id="mcconsole" style="width:100%;height:400px;background-color:#000;color:#ccc;font-family:Courier, serif;font-size:12px;overflow-y:scroll">
                <?php foreach ($this->server->getLog() as $log) { ?>
                    <div><?=$log?></div>
                <?php } ?>
            </div>
            <form class="js-ajax" target="/ajax/cmd">
                <input type="hidden" name="server" value="<?=$this->server->getName()?>">
                <input autocomplete="off" name="cmd" style="width:100%">
            </form>
        </div>
    </div>

</div>


<script>
    $(function() {

        var height = $('#mcconsole')[0].scrollHeight;
        $('#mcconsole').scrollTop(height);



        $('.js-ajax').submit( function(e) {
            e.preventDefault();
            $.post($(this).attr('target'), $(this).serialize(), function(data) {
                $('input[name=cmd]').val('');
            });
        });

    });
</script>