<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3><?=htmlspecialchars($this->server->getName())?></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <?php include '_tabs.phtml'; ?>
                <div class="x_panel" style="margin-top:0;">

                    <div id="mcconsole" style="width:100%;height:400px;background-color:#000;color:#ccc;font-family:Courier, serif;font-size:12px;overflow-y:scroll">
                        <?php foreach ($this->server->getLog() as $log) { ?>
                            <div><?=$log?></div>
                        <?php } ?>
                    </div>
                    <form class="js-ajax" target="/ajax/cmd">
                        <input type="hidden" name="server" value="<?=$this->server->getName()?>">
                        <input name="cmd" style="width:100%">
                    </form>





                </div>
            </div>
        </div>


    </div>
</div>
<!-- /page content -->
<script>
    $(function() {

        var height = $('#mcconsole')[0].scrollHeight;
        $('#mcconsole').scrollTop(height);


        myIo.emit('join', '<?=$this->server->getName()?>');

        $('.js-ajax').submit( function(e) {
            e.preventDefault();
            $.post($(this).attr('target'), $(this).serialize(), function(data) {
                $('input[name=cmd]').val('');
            });
        });

    });
</script>