
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <?php include '_tabs.phtml'; ?>
                <div class="card">
                    <div class="header">
                    </div>

                        <div class="content">
                            <div id="mcconsole" style="width:100%;height:400px;background-color:#000;color:#ccc;font-family:Courier, serif;font-size:12px;overflow-y:scroll">
                                <?php foreach ($this->server->getLog() as $log) { ?>
                                    <div><?=$log?></div>
                                <?php } ?>
                            </div>
                            <form class="js-ajax" target="/ajax/cmd">
                                <input type="hidden" name="server" value="<?=$this->server->getName()?>">
                                <input name="cmd" style="width:100%">
                            </form>
                        </div>
                </div>

            </div>


        </div>
    </div>
</div>

<script>
    $(function() {

        var height = $('#mcconsole')[0].scrollHeight;
        $('#mcconsole').scrollTop(height);


        myIo.emit('join', '<?=$this->server->getName()?>');

        $('.js-ajax').submit( function(e) {
            e.preventDefault();
            $.post($(this).attr('target'), $(this).serialize(), function(data) {
                $('input[name=cmd]').val('');
            });
        });

    });
</script>