<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                    </div>



                    <form class="form-horizontal form-label-left" method="post">

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" name="name" <?=empty($this->formdata['name'])?'':'disabled'?> value="<?=htmlspecialchars($this->formdata['name'])?>" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="host">Host</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="host" class="form-control col-md-7 col-xs-12">
                                    <?php foreach ($this->hosts as $host) { ?>
                                        <option value="<?=htmlspecialchars($host->getName())?>"><?=htmlspecialchars($host->getName() . ' | ' . $host->get('hostname') )?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="jar">Jar</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="jar" class="form-control col-md-7 col-xs-12">
                                    <?php foreach ($this->binaries as $b) { ?>
                                        <option value="<?=htmlspecialchars($b)?>"><?=htmlspecialchars($b)?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Memory</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" name="memory" value="<?=htmlspecialchars($this->formdata['memory'])?>" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="submit" class="btn btn-success" value="Submit">
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>


