<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-striped">
                            <thead>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Host</th>
                            <th>Status</th>
                            <th>Actions</th>
                            </thead>
                            <tbody>
                            <?php foreach ($this->servers as $s) {  ?>
                                <tr>
                                    <td><?=$s->get('id')?></td>
                                    <td><a href="/server/<?=$s->get('name')?>/general"><?=$s->get('name')?></a></td>
                                    <td><?=$s->get('host')?></td>
                                    <td><?=$s->getStatus()?></td>
                                    <td>...</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="content">
                        <a href="/server/add"><button class="btn btn-success">Create new server</button></a>
                        </div>
                    </div>
                </div>


            </div>


        </div>
    </div>
</div>
