<div class="card">


    <div class="card-table">

        <table class="table table-striped">
            <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Host</th>
            <th>Status</th>
            <th>Actions</th>
            </thead>
            <tbody>
            <?php foreach ($this->servers as $s) {  ?>
                <tr>
                    <td><?=$s->get('id')?></td>
                    <td><a href="/server/<?=$s->get('name')?>/general"><?=$s->get('name')?></a></td>
                    <td><?=$s->get('host')?></td>
                    <td><?=$s->getStatus()?></td>
                    <td>...</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>




    </div>
    <div class="card-footer text-center">
        <a href="/server/add"><button class="btn btn-success btn-center">Create new server</button></a>
    </div>
</div>

