<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <?php include '_tabs.phtml'; ?>
                <div class="card">
                    <div class="header">
                    </div>

                        <?php $ops = $this->server->getOps();
                        if (count($ops) == 0) { ?>
                            <div class="content">
                                No ops.
                            </div>
                        <?php } else { ?>
                            <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <thead>
                                <th>Avatar</th>
                                <th>Name</th>
                                <?php if ($this->server->isRunning()) { ?><th>Action</th><?php } ?>
                                </thead>
                                <tbody>
                                <?php foreach ($ops as $op) { ?>
                                    <tr>
                                        <td><img src="data:image/png;base64,<?=\Mooshroom\Mojang::getHead($op['uuid'])?>"></td>
                                        <td><?=$op['name']?><br><?=$op['uuid']?></td>
                                        <?php if ($this->server->isRunning()) { ?>
                                            <td><a href="/server/<?=$this->server->getName()?>/whitelist?username=<?=$op['name']?>">delete</a></td>
                                        <?php } ?>
                                    </tr>
                                <?php } ?>
                                </tbody>
                            </table>
                            </div>
                        <?php } ?>

                </div>

                <div class="card">
                    <div class="content">
                        <?php if ($this->server->isRunning()) { ?>
                            <form method="post" class="upform">
                                <div class="input-group">
                                    <input type="text" name="username" class="form-control border-input">
                                    <span class="input-group-btn">
                                                <input type="submit" class="form-control btn btn-info btn-fill btn-wd" value="add" >
                                          </span>
                                </div>
                            </form>
                        <?php } else { ?>
                            You can not edit the ops as long as the server is not running.
                        <?php } ?>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>


