<div class="col-md-12">

    <?php include '_control.phtml'; ?>

    <div class="card">

        <?php include '_tabs.phtml'; ?>

        <div class="card-content">


            <?php $ops = $this->server->getOps(); ?>


            <table class="table table-responsive table-striped">
                <thead>
                <th>Avatar</th>
                <th>Name</th>
                <th>Actions</th>
                </thead>
                <tbody>
                <?php if (count($ops) == 0) { ?>
                    <tr class="">
                        <td colspan="3">No ops yet.</td>
                    </tr>
                <?php } ?>
                <?php foreach ($ops as $op) { ?>
                    <tr class="op-<?=$op['name']?>">
                        <td><img src="data:image/png;base64,<?=\Mooshroom\Mojang::getHead($op['uuid'])?>"></td>
                        <td><?=$op['name']?><br><?=$op['uuid']?></td>
                        <?php if ($this->server->isRunning()) { ?>
                            <td>
                                <a href="#" data-server="<?=$this->server->getId()?>" data-cmd="deop <?=$op['name']?>" class="js-scmd btn btn-simple btn-danger btn-icon remove"><i class="ti-close"></i></a>
                            </td>
                        <?php } ?>
                    </tr>
                <?php } ?>
                </tbody>
            </table>



        </div>

        <div class="card-content">
            <form method="post" id="addwl">
                <div class="input-group">
                    <input id="input-field" type="text" name="username" class="form-control border-input">
                    <span class="input-group-btn">
                                <input type="submit" class="btn btn-info" value="add" >
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    $('.js-scmd').click(function() {
        self = this;
        $.post( '/ajax/scmd',
            {cmd: $(this).data('cmd'), server: $(this).data('server') },
            function (data) {
            }
        );
    });

    $('#addwl').submit(function(e) {
        e.preventDefault();
        $.post('/ajax/scmd', { server: <?=$this->server->getId()?>, cmd: 'op ' + $('#input-field').val() }, function (data) {
            $('#input-field').val('')
        });

    });

</script>