<div class="col-md-12">

    <?php include '_control.phtml'; ?>

    <div class="card">

        <?php include '_tabs.phtml'; ?>

        <div class="card-content">

            <input class="js-plugins">

            <?php
                $plugins = $this->server->getPlugins();
                foreach ($plugins as $name => $status) { ?>
                <div style="margin:5px;">
                    <input type="checkbox" class="js-switch js-plugin" name="<?=htmlspecialchars($name)?>" <?=($status?'checked':'')?> /> <?=htmlspecialchars($name)?><br>
                </div>
            <?php } ?>
            <?php if (count($plugins) == 0) { ?>
                No Plugins installed.
            <?php } ?>
        </div>

    </div>
</div>

<script>

    var substringMatcher = function(q, cb) {

        var strs = <?=json_encode( \Mooshroom\Model\Binaries::getAll('plugins'))?>;
        var matches, substringRegex;
        matches = [];
        substrRegex = new RegExp(q, 'i');
        $.each(strs, function(i, str) {
            if (substrRegex.test(str)) {
                matches.push({name: str});
            }
        });
        cb(matches);
    };

    $('input.js-plugins').tagsinput({
        tagClass: function(item) {
            return "label label-primary label-success";
        },
        typeaheadjs: {
            name: 'aclgroups',
            displayKey: 'name',
            valueKey: 'name',
            source: substringMatcher //aclgroups.ttAdapter()
        },

    });
</script>

