<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3><?=htmlspecialchars($this->server->getName())?></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <?php include '_tabs.phtml'; ?>
                <div class="x_panel" style="margin-top:0;">

                    <div id="myTabContent" class="tab-content">



                                <br>
                                <form class="form-horizontal form-label-left" method="post">

                                    <?php foreach ($this->server->getServerProperties()->getData() as $k => $v) { ?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sp[<?=htmlspecialchars($k)?>]"><?=htmlspecialchars($k)?></label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">

                                                <?php if ($v['type'] == 'boolean') { ?>
                                                    <label style="margin-top:6px;">
                                                        <input <?=($v['value'] == 'true') ? 'checked' : '' ?> type="radio" name="sp[<?=htmlspecialchars($k)?>]" value="true"> true
                                                    </label>
                                                    &nbsp;&nbsp;
                                                    <label>
                                                        <input <?=($v['value'] == 'false') ? 'checked' : '' ?> type="radio" name="sp[<?=htmlspecialchars($k)?>]" value="false"> false
                                                    </label>


                                                <?php } else if (preg_match('/^integer/', $v['type'])) { ?>
                                                    <input type="text" name="sp[<?=htmlspecialchars($k)?>]" value="<?=htmlspecialchars($v['value'])?>" class="form-control col-md-7 col-xs-12">
                                                <?php } else if ($v['type'] == 'string') { ?>
                                                    <input type="text" name="sp[<?=htmlspecialchars($k)?>]" value="<?=htmlspecialchars($v['value'])?>" class="form-control col-md-7 col-xs-12">
                                                <?php } else { ?>
                                                    unknown type
                                                <?php } ?>

                                            </div>
                                        </div>
                                    <?php } ?>

                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                            <input type="submit" class="btn btn-success" name="submit" value="Save">
                                            <input type="submit" class="btn btn-success" name="submit" value="Save and Restart">
                                        </div>
                                    </div>
                                </form>


                    </div>

                </div>
            </div>
        </div>


    </div>
</div>
<!-- /page content -->
