<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <?php include '_tabs.phtml'; ?>
                <div class="card">

                    <div class="content">
                        <form class="form-horizontal form-label-left" method="post">

                            <?php foreach ($this->server->getServerProperties()->getData() as $k => $v) { ?>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sp[<?=htmlspecialchars($k)?>]"><?=htmlspecialchars($k)?></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">

                                        <?php if ($v['type'] == 'boolean') { ?>
                                            <label style="margin-top:6px;">
                                                <input <?=($v['value'] == 'true') ? 'checked' : '' ?> type="radio" name="sp[<?=htmlspecialchars($k)?>]" value="true"> true
                                            </label>
                                            &nbsp;&nbsp;
                                            <label>
                                                <input <?=($v['value'] == 'false') ? 'checked' : '' ?> type="radio" name="sp[<?=htmlspecialchars($k)?>]" value="false"> false
                                            </label>


                                        <?php } else if (preg_match('/^integer/', $v['type'])) { ?>
                                            <input type="text" name="sp[<?=htmlspecialchars($k)?>]" value="<?=htmlspecialchars($v['value'])?>" class="form-control col-md-7 col-xs-12">
                                        <?php } else if ($v['type'] == 'string') { ?>
                                            <input type="text" name="sp[<?=htmlspecialchars($k)?>]" value="<?=htmlspecialchars($v['value'])?>" class="form-control col-md-7 col-xs-12">
                                        <?php } else { ?>
                                            unknown type
                                        <?php } ?>

                                    </div>
                                </div>
                            <?php } ?>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <input type="submit" class="btn btn-success" name="submit" value="Save">
                                    <input type="submit" class="btn btn-success" name="submit" value="Save and Restart">
                                </div>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
